### ISSUE TITLE
Dataset link not working

### ISSUE THREAD

**Issue by gilmartinspinheiro** [baudm/HomographyNet#1]
Can you please provide a working link for the dataset download explicit in the How To in the "Dataset" Folder?
The way you have done, only people in your network can download it!

Thanks

**Comment by baudm** [comment]
Hi, sorry but that link is no longer available. It was for sharing the
dataset with my class only. Easiest thing to do is download a COCO dataset
and generate a HomographyNet dataset using the script here. It'll be fast,
don't worry (took just 8 minutes for 500k images in my machine)

On Dec 5, 2017 5:42 AM, "gilmartinspinheiro" <notifications@github.com>
wrote:

Can you please provide a working link for the dataset download explicit in
the How To in the "Dataset" Folder?
The way you have done, only people in your network can download it!

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/baudm/HomographyNet/issues/1>, or mute the thread
